# Generated by Django 4.2.15 on 2024-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(help_text='分类Id', max_length=11, primary_key=True, serialize=False, verbose_name='分类Id')),
                ('categoryName', models.CharField(help_text='分类名称', max_length=24, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '原料分类信息',
                'verbose_name_plural': '原料分类信息',
                'ordering': ['categoryId'],
            },
        ),
    ]
