# Generated by Django 4.2.15 on 2024-08-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categoryId'], 'verbose_name': '原料分类名信息', 'verbose_name_plural': '原料分类名信息'},
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.AutoField(help_text='分类Id', primary_key=True, serialize=False, verbose_name='分类Id'),
        ),
        migrations.CreateModel(
            name='MaterialLinkCategory',
            fields=[
                ('materialId', models.IntegerField(help_text='原料Id', primary_key=True, serialize=False, verbose_name='原料Id')),
                ('categoryId', models.ForeignKey(help_text='分类Id', on_delete=django.db.models.deletion.CASCADE, to='material_category.category', verbose_name='分类Id')),
            ],
            options={
                'verbose_name': '原料绑定分类信息',
                'verbose_name_plural': '原料绑定分类信息',
                'ordering': ['categoryId', 'materialId'],
            },
        ),
    ]
