# Generated by Django 4.2.15 on 2024-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_category', '0002_alter_category_options_alter_category_categoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intoStatisticsFlag',
            field=models.BooleanField(default=0, help_text='是否纳入统计', verbose_name='是否纳入统计'),
            preserve_default=False,
        ),
    ]
