# Generated by Django 4.2.15 on 2024-08-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_category', '0003_category_intostatisticsflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(help_text='分类名称', max_length=24, unique=True, verbose_name='分类名称'),
        ),
    ]
